name: Generate Technical Docs

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Generate docs
        run: npm run docs

      - name: Commit updated docs
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs/'
          message: 'Auto-update generated docs'
