name: github-actions-template
run-name: ${{ github.actor }} is running GitHub Actions templates

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - release/*
      - feature/*
    paths:
        - 'force-app/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
        - master
    paths:
        - 'force-app/**'
      
jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    # container:
    #  image: salesforce/salesforcedx:latest-full
      
    steps:
    
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install CLI
        run: |
          npm install
          npm install sfdx-cli --global
        #- name: Decrypt server key
        #run: |
            #Decrypt server key
           # openssl enc -nosalt -aes-256-cbc -d -in ${{ secrets.ENCRYPTION_KEY_FILE }} -out ${{ secrets.JWT_KEY_FILE }} -base64 -K ${{ secrets.DECRYPTION_KEY }} -iv ${{ secrets.DECRYPTION_IV }}
      
      #- name: Authenticate Salesforce ORG
        #run: |
          #sfdx force --help
          #sfdx force:auth:jwt:grant --clientid ${{ secrets.HUB_CONSUMER_KEY }} --jwtkeyfile  ${{ secrets.JWT_KEY_FILE }} --username ${{ secrets.HUB_USER_NAME }} --setdefaultdevhubusername -a HubOrg
      - name: Run Code Analysis
        run:  sfdx scanner:run --target "force-app/main/default/classes" --format "csv" --outfile "Apexviolation.csv"
      
      - name: Upload the CSV file as an artifact
        uses: actions/upload-artifact@v2
        with:
         name: apex_violation_csv
         path: Apexviolation.csv
      
      - name: lw Code Analysis
        run:  sfdx scanner:run --target "force-app/main/default/lwc" --format "csv" --outfile "lwcviolation.csv"

      - name: Upload the CSV file as an artifact
        uses: actions/upload-artifact@v2
        with:
         name: lwc_violation_csv
         path: lwcviolation.csv
      
      - name: Aura Code Analysis
        run:  sfdx scanner:run --target "force-app/main/default/aura" --format "csv" --outfile "auraviolation.csv"

      - name: Upload the CSV file as an artifact
        uses: actions/upload-artifact@v2
        with:
         name: aura_violation_csv
         path: auraviolation.csv
      
      - name: Run Apex Tests and Export Coverage
        run: |
          sfdx apex:run:test -l RunLocalTests -c -w 30
          sfdx force:apex:test:report --resultformat human --outputdir ./test-results
          mv ./test-results/apex-code-coverage.csv ./test-results/test-coverage.csv
  
      
      
      