name: github-actions-template
run-name: ${{ github.actor }} is running GitHub Actions templates

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - release/*
      - feature/*
    paths:
        - 'force-app/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
        - master
    paths:
        - 'force-app/**'
      
jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    # container:
    #  image: salesforce/salesforcedx:latest-full
      
    steps:
    
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install CLI
        run: |
          npm install
          npm install sfdx-cli --global
          
      # Run PMD scan
      - name: 'Run PMD scan'
        uses: pmd/pmd-github-action@v1
        id: pmd
        with:
            sourcePath: 'force-app'
            rulesets: 'ruleset.xml'
            analyzeModifiedFilesOnly: false

      # Check for PMD violations
      - name: 'Check for PMD violations'
        run: |
          echo "PMD violations count: ${{ steps.pmd.outputs.violations }}"
          echo "Writing PMD violations to file"
          echo "ruleSet,file,line,description" > pmd_violations.csv
          echo "${{ steps.pmd.outputs.violationsCsv }}" >> pmd_violations.csv

      # Upload PMD violations report as an artifact
      - name: Upload PMD Violations Report
        uses: actions/upload-artifact@v2
        with:
          name: pmd-violations
          path: pmd_violations.csv
                  
      #- name: Decrypt server key
        #run: |
            #Decrypt server key
           # openssl enc -nosalt -aes-256-cbc -d -in ${{ secrets.ENCRYPTION_KEY_FILE }} -out ${{ secrets.JWT_KEY_FILE }} -base64 -K ${{ secrets.DECRYPTION_KEY }} -iv ${{ secrets.DECRYPTION_IV }}
      
      #- name: Authenticate Salesforce ORG
        #run: |
          #sfdx force --help
          #sfdx force:auth:jwt:grant --clientid ${{ secrets.HUB_CONSUMER_KEY }} --jwtkeyfile  ${{ secrets.JWT_KEY_FILE }} --username ${{ secrets.HUB_USER_NAME }} --setdefaultdevhubusername -a HubOrg
      - name: Run Code Analysis
        run:  sfdx scanner:run --target "force-app/main/default/classes" --format "csv" --outfile "Apexviolation.csv"
      
      - name: Upload the CSV file as an artifact
        uses: actions/upload-artifact@v2
        with:
         name: apex_violation_csv
         path: Apexviolation.csv